export const RESET_ACTIVITY_STATE = 'RESET_ACTIVITY_STATE';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_SELECTED_PANEL_HOLD = 'SET_SELECTED_PANEL_HOLD';
export const SHOW_HOLDS_SAVED_NOTE = 'SHOW_HOLDS_SAVED_NOTE';
export const SET_BOARD_LIST_INDEX = 'SET_BOARD_LIST_INDEX';
export const SET_SHOW_BOARD_ADD = 'SET_SHOW_BOARD_ADD';
export const SET_SHOW_BOARD_NAME_EDIT = 'SET_SHOW_BOARD_NAME_EDIT';
export const SET_SHOW_BOARD_DELETE_CONFIRM = 'SET_SHOW_BOARD_DELETE_CONFIRM';