export const RESET_ACTIVITY_STATE = 'RESET_ACTIVITY_STATE';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_SELECTED_PANEL_HOLD = 'SET_SELECTED_PANEL_HOLD';
export const SHOW_HOLDS_SAVED_NOTE = 'SHOW_HOLDS_SAVED_NOTE';