export const authConstants = {
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    VERIFICATION_EMAIL_SUCCESS: 'VERIFICATION_EMAIL_SUCCESS',
    NEW_PASSWORD_CONFIRMED: 'NEW_PASSWORD_CONFIRMED',
    USERNAME_REMINDER_SUCCESS: 'USERNAME_REMINDER_SUCCESS',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    SET_SHOW_REG_FORM: 'SET_SHOW_REG_FORM',
    FOCUS_USERNAME_INPUT: 'FOCUS_USERNAME_INPUT',
    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',
    SET_REGISTRATION_ERRORS: 'SET_REGISTRATION_ERRORS'
};

export const REGISTER_FAILURE = authConstants.REGISTER_FAILURE;
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_SUCCESS = authConstants.LOGIN_SUCCESS;
export const SET_AWAITING_AUTH = 'SET_AWAITING_AUTH';