export const FETCH_SUMMARY_DATA_FAILURE = 'FETCH_SUMMARY_DATA_FAILURE';
export const SET_PROFILE_BOARDS = 'SET_PROFILE_BOARDS';
export const INITIAL_LOAD_DONE = 'INITIAL_LOAD_DONE';
export const SET_TEMP_LISTS = 'SET_TEMP_LISTS';
export const RESET_PROFILE_STATE = 'RESET_PROFILE_STATE';