export const FETCH_SUMMARY_DATA_BEGIN = 'FETCH_SUMMARY_DATA_BEGIN';
export const FETCH_SUMMARY_DATA_SUCCESS = 'FETCH_SUMMARY_DATA_SUCCESS';
export const FETCH_SUMMARY_DATA_FAILURE = 'FETCH_SUMMARY_DATA_FAILURE';
export const SET_PROFILE_BOARDS = 'SET_PROFILE_BOARDS';
export const INITIAL_LOAD_DONE = 'INITIAL_LOAD_DONE';
export const SET_TEMP_LISTS = 'SET_TEMP_LISTS';
