export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    VERIFICATION_EMAIL_SUCCESS: 'VERIFICATION_EMAIL_SUCCESS',
    NEW_PASSWORD_CONFIRMED: 'NEW_PASSWORD_CONFIRMED',
    USERNAME_REMINDER_SUCCESS: 'USERNAME_REMINDER_SUCCESS',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    SET_SHOW_REG_FORM: 'SET_SHOW_REG_FORM',
    FOCUS_USERNAME_INPUT: 'FOCUS_USERNAME_INPUT',
    CLEAR_EXT_FORM_ERRORS: 'CLEAR_EXT_FORM_ERRORS',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};

export const REGISTER_REQUEST = userConstants.REGISTER_REQUEST;
export const REGISTER_SUCCESS = userConstants.REGISTER_SUCCESS;
export const REGISTER_FAILURE = userConstants.REGISTER_FAILURE;
export const CLEAR_EXT_FORM_ERRORS = userConstants.CLEAR_EXT_FORM_ERRORS;
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_EMAIL_UPDATE = 'USER_EMAIL_UPDATE';